blinklabs-io/cardano-up

.github/dependabot.yml
.github/workflows/ci-docker.yml
.github/workflows/conventional-commits.yml
.github/workflows/go-test.yml
.github/workflows/golangci-lint.yml
.github/workflows/publish.yml
.gitignore
CODEOWNERS
Dockerfile
Makefile
cmd/cardano-up/main.go
go.mod
internal/version/version.go

feat: initial repo structure

---

pkgmgr/env.go
pkgmgr/pkgmgr.go
pkgmgr/state.go

feat: package manager state support

---

cmd/cardano-up/main.go
cmd/cardano-up/version.go
internal/consolelog/consolelog.go

feat: prettier console output

---

go.mod
go.sum
pkgmgr/installed_package.go
pkgmgr/package.go
pkgmgr/pkgmgr.go
pkgmgr/state.go

feat: store info about installed packages

---

cmd/cardano-up/main.go
cmd/cardano-up/uninstall.go
pkgmgr/docker.go
pkgmgr/package.go
pkgmgr/pkgmgr.go

feat: basic uninstall support

---

pkgmgr/docker.go
pkgmgr/error.go
pkgmgr/package.go

feat: check for Docker connectivity on install

---

cmd/cardano-up/install.go

feat: ensure that network is set on install

---

pkgmgr/registry.go

fix: make cardano-node port map dynamic

---

pkgmgr/registry.go

feat: mithril-client package

---

cmd/cardano-up/context.go
cmd/cardano-up/install.go
go.mod
go.sum
pkgmgr/context.go
pkgmgr/error.go
pkgmgr/pkgmgr.go

feat: network validation

---

cmd/cardano-up/uninstall.go
pkgmgr/error.go
pkgmgr/pkgmgr.go
pkgmgr/resolver.go

feat: resolve deps on uninstall

---

pkgmgr/docker.go
pkgmgr/pkgmgr.go

feat: show docker image pull progress

---

cmd/cardano-up/list.go

feat: show compat info in list-available

---

pkgmgr/package.go
pkgmgr/registry.go

feat: naive binary wrapper on file install

---

pkgmgr/installed_package.go
pkgmgr/package.go
pkgmgr/pkgmgr.go
pkgmgr/registry.go

feat: package post-install notes from template

---

cmd/cardano-up/info.go
cmd/cardano-up/main.go
pkgmgr/pkgmgr.go

feat: info command

---

cmd/cardano-up/install.go
cmd/cardano-up/main.go
cmd/cardano-up/upgrade.go
pkgmgr/error.go
pkgmgr/installed_package.go
pkgmgr/pkgmgr.go
pkgmgr/registry.go
pkgmgr/resolver.go

feat: upgrade support

---

pkgmgr/package.go

feat: pre-create package dirs on install

---

pkgmgr/config.go
pkgmgr/package.go
pkgmgr/pkgmgr.go
pkgmgr/registry.go

feat: filter packages by OS/arch/engine tags

---

pkgmgr/docker.go
pkgmgr/package.go

feat: remove docker image on uninstall

---

pkgmgr/docker.go
pkgmgr/error.go
pkgmgr/package.go

fix: check for container not existing

---

pkgmgr/error.go
pkgmgr/package.go
pkgmgr/registry.go
pkgmgr/resolver.go
pkgmgr/template.go

feat: conditional install steps

---

pkgmgr/package.go
pkgmgr/package_test.go

feat: support for reading packages from disk

---

pkgmgr/config.go
pkgmgr/pkgmgr.go
pkgmgr/registry.go
pkgmgr/registry_test.go

feat: package registry support

---

pkgmgr/config.go
pkgmgr/package.go
pkgmgr/registry.go

feat: shared context directory

---

pkgmgr/installed_package.go
pkgmgr/package.go
pkgmgr/pkgmgr.go
pkgmgr/registry.go

feat: package outputs

---

packages/cardano-node/cardano-node-8.7.3.yaml
packages/mithril-client/mithril-client-0.5.17.yaml
packages/mithril-client/mithril-client-0.7.0.yaml
packages/ogmios/ogmios-v6.1.0.yaml
packages/test-packageA/test-packageA-1.0.2.yaml
packages/test-packageA/test-packageA-1.0.3.yaml
packages/test-packageA/test-packageA-2.1.3.yaml
packages/test-packageB/test-packageB-0.1.0.yaml
pkgmgr/config.go
pkgmgr/error.go
pkgmgr/package.go
pkgmgr/registry.go

feat: move packages to separate files

---

cmd/cardano-up/context.go
cmd/cardano-up/down.go
cmd/cardano-up/info.go
cmd/cardano-up/install.go
cmd/cardano-up/list.go
cmd/cardano-up/main.go
cmd/cardano-up/uninstall.go
cmd/cardano-up/up.go
cmd/cardano-up/upgrade.go

feat: allow configuring registry URL/dir

---

cmd/cardano-up/context.go
pkgmgr/pkgmgr.go

feat: command to show env for context

---

pkgmgr/package.go

feat: expose container ports for package template

---

pkgmgr/pkgmgr.go

feat: expose context env vars for templates

---

pkgmgr/registry.go

feat: show message when fetching registry ZIP

---

packages/cardano-node/cardano-node-8.7.3.yaml
packages/cardano-node/files/cardano-cli.sh.gotmpl
pkgmgr/package.go
pkgmgr/registry.go
pkgmgr/registry_test.go

feat: install step file external source

---

cmd/cardano-up/logs.go
cmd/cardano-up/main.go
pkgmgr/docker.go
pkgmgr/error.go
pkgmgr/pkgmgr.go

feat: logs command

---

cmd/cardano-up/install.go
cmd/cardano-up/up.go

feat: install cardano-node on 'up' when no packages installed

---

cmd/cardano-up/context.go
cmd/cardano-up/uninstall.go
pkgmgr/pkgmgr.go

feat: uninstall on delete context

---

packages/cardano-node/files/cardano-cli.sh.gotmpl

feat: allow access to host paths in cardano-cli wrapper

---

packages/cardano-node/cardano-node-8.7.3.yaml

feat: provide cardano-node socket path as output

---

README.md

docs: basic usage

---

pkgmgr/docker.go
pkgmgr/package.go

This reverts commit ff64c338d7c1ae1050d06aec3c118ee7670ffd49.
Keeps `io` package
Keeps fix pkgDataDir

Revert "feat: use docker for cleanup (#92)"

---

pkgmgr/error.go
pkgmgr/package.go
pkgmgr/resolver.go

fix: don't allow installing empty package

---

cmd/cardano-up/main.go
cmd/cardano-up/update.go
pkgmgr/pkgmgr.go

feat: command to update package registry cache

---

pkgmgr/package.go

feat: precreate container bind mount host paths

---

cmd/cardano-up/validate.go
pkgmgr/config.go
pkgmgr/pkgmgr.go

fix: only load packages when needed

---

README.md

docs: add description for each subcommand to README

---

go.mod
go.sum
packages/cardano-node/cardano-node-8.9.1.yaml
packages/mithril-client/files/mithril-client.sh.gotmpl
pkgmgr/package.go

feat: use mithril-client in cardano-node preinstall

---

README.md

docs: package maintenance

---

packages/cardano-cli/files/cardano-cli.sh.gotmpl
packages/mithril-client/files/mithril-client.sh.gotmpl

fix: volume map to default Docker Deskotp file sharing (/Users)

---

cmd/cardano-up/context.go
cmd/cardano-up/install.go
cmd/cardano-up/list.go
cmd/cardano-up/logs.go
cmd/cardano-up/main.go
cmd/cardano-up/uninstall.go
cmd/cardano-up/up.go
cmd/cardano-up/validate.go
cmd/cardano-up/version.go
pkgmgr/config_test.go
pkgmgr/docker.go
pkgmgr/error.go
pkgmgr/installed_package.go
pkgmgr/package.go
pkgmgr/package_test.go
pkgmgr/pkgmgr.go
pkgmgr/registry.go
pkgmgr/registry_test.go
pkgmgr/resolver.go
pkgmgr/resolver_test.go
pkgmgr/template.go

No changes by me, just `make golines`

chore: golines

---

packages/ogmios/ogmios-v6.4.0.yaml

chore(packages): upgrade ogmios to 6.4.0

---

packages/dolos/files/daemon.toml.gotmpl

fix: dolos peer address for mainnet
