cmd/cardano-up/main.go, cmd/cardano-up/version.go, go.mod, go.sum
=> feat: initial CLI framework

.github/workflows/go-test.yml, .github/workflows/publish.yml, cmd/cardano-up/main.go, cmd/cardano-up/test.go, go.mod, pkgmgr/config.go, pkgmgr/config_test.go, pkgmgr/pkgmgr.go
=> feat: initial config framework

cmd/cardano-up/context.go, cmd/cardano-up/main.go, pkgmgr/context.go, pkgmgr/env.go, pkgmgr/error.go, pkgmgr/pkgmgr.go, pkgmgr/state.go
=> feat: context support

cmd/cardano-up/install.go, pkgmgr/pkgmgr.go
=> feat: set context network on install

pkgmgr/config.go, pkgmgr/package.go, pkgmgr/pkgmgr.go, pkgmgr/registry.go, pkgmgr/template.go
=> feat: template support

pkgmgr/config.go, pkgmgr/config_test.go, pkgmgr/package.go, pkgmgr/registry.go
This modifies some paths. We use ~/.local/share for data, which is the default location for XDG_DATA_HOME on Linux.
=> feat: cardano-node data persistence

cmd/cardano-up/down.go, cmd/cardano-up/main.go, cmd/cardano-up/up.go, pkgmgr/package.go, pkgmgr/pkgmgr.go
Fixes #14 
```
./cardano-up down
Stopping container cardano-node-8.7.3-default-cardano-node
➜  cardano-up git:(feat/start-stop) ✗ ./cardano-up up
Starting Docker container cardano-node-8.7.3-default-cardano-node
➜  cardano-up git:(feat/start-stop) ✗ ./cardano-up list
Installed packages (from context "default"):
Name                 Version      Context         Description
cardano-node         8.7.3        default         Cardano node software by Input Output Global
default
```
=> feat: add up/down commands

pkgmgr/package.go, pkgmgr/registry.go
=> feat: support for pulling docker image without service

pkgmgr/registry.go
Installing package ogmios (= v6.1.0)
v6.1.0: Pulling from cardanosolutions/ogmios
=> feat: add Ogmios package

cmd/cardano-up/uninstall.go, pkgmgr/package.go, pkgmgr/pkgmgr.go
=> feat: cleanup data on uninstall

pkgmgr/package.go, pkgmgr/pkgmgr.go
=> feat: manage binary symlinks when changing context

packages/ogmios/ogmios-v6.1.0.yaml
```
94e402a597d3   ghcr.io/blinklabs-io/cardano-node:8.7.3   "/usr/local/bin/entr…"   20 minutes ago   Up 20 minutes             12788/tcp, 12798/tcp, 0.0.0.0:63598->3001/tcp   cardano-node-8.7.3-default-cardano-node
6d3d8942b3c9   cardanosolutions/ogmios:v6.1.0            "ogmios --log-level …"   20 minutes ago   Up 20 minutes (healthy)   0.0.0.0:60911->1337/tcp                         ogmios-v6.1.0-default-ogmios
```
=> fix(package): fix config for Ogmios to match Context.Network 

pkgmgr/docker.go
=> feat: create container with current uid,gid

.github/workflows/package-validate.yml, cmd/cardano-up/main.go, cmd/cardano-up/validate.go, pkgmgr/config.go, pkgmgr/error.go, pkgmgr/package.go, pkgmgr/pkgmgr.go, pkgmgr/registry.go, pkgmgr/registry_test.go
=> feat: package file validation

packages/ogmios/ogmios-v6.1.0.yaml
Closes #162 and #164 
Test
```bash
./cardano-up context env | grep -i "ogmios"
export OGMIOS_HEALTH_URL=http://localhost:50720/health
export OGMIOS_URL=http://localhost:50720
```
=> feat(packages): update Ogmios package with outputs and dependencies

README.md
=> docs: add contexts section to README

pkgmgr/package.go, pkgmgr/pkgmgr.go
=> feat: package install/uninstall hooks

packages/cardano-node/cardano-node-8.9.1.yaml, packages/kupo/kupo-2.8.0.yaml
Test
```
docker ps -a
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                    PORTS                                           NAMES
be3bbaf1becb   cardanosolutions/kupo:2.8.0              "kupo --node-socket …"   13 seconds ago   Up 12 seconds (healthy)   0.0.0.0:64068->1442/tcp                         kupo-2.8.0-default-kupo
a26a935778ee   ghcr.io/blinklabs-io/cardano-node:8.9.1   "/usr/local/bin/entr…"   51 seconds ago   Up 46 seconds             12788/tcp, 12798/tcp, 0.0.0.0:63989->3001/tcp   cardano-node-8.9.1-default-cardano-node
./cardano-up context env | grep -i "KUPO"
export KUPO_HEALTH_URL=http://localhost:64068/health
export KUPO_URL=http://localhost:64068
curl -s http://localhost:64068/health …
```
=> feat(packages): add Kupo package

README.md
I also moved the install from source to a "Development" section
=> docs: recommend using .local/bin and installing from binary

packages/dolos/dolos-0.7.0.yaml, packages/dolos/files/daemon.toml.gotmpl
=> feat: add Dolos package

packages/dolos/dolos-0.7.0.yaml, packages/dolos/files/daemon.toml.gotmpl
This closes #209 but also removes the dependency on a local cardano-node, as it's not necessary for Dolos.
=> fix(packages): dolos outputs with static ports

packages/dolos/dolos-0.7.0.yaml, packages/dolos/files/daemon.toml.gotmpl
A few quick changes
- depend on cardano-configs
- add a /data persistent per-version directory and update config
- use static host ports (see #231)
- serve correct ouroboros network magic
Closes #27
=> fix: dolos start and persistence

pkgmgr/docker.go
This probably isn't the correct way to do this, but it worked in all my tests and we don't really care about the actual exposed ports. This should also work for the case where we use ports which weren't originally exposed in the image.
This is related to #209 and why we weren't getting all of our ports. They weren't getting mapped into the container correctly. This solves that issue correctly and closes #231.
=> fix: map ports as exposed ports always

packages/dolos/dolos-0.7.0.yaml
This resolves the issue with Dolos starting up.
- Write config file before starting container
- Remove static host port mapping to allow multiple instances
- Remove redundant `dolos-` prefix from output names
- Restore port lookup to get local port, requires #237 and reverts #226 
Closes #227
=> fix(packages): dolos reorder steps to resolve start issue

pkgmgr/registry.go
=> fix: check for parent dir reference when extracting cache

README.md, pkgmgr/package.go
This will allow us to use the full path to binaries from packages we ship, ensuring they execute correctly in environments where the user has not modified their path.
=> feat: expose the bin directory to packages

pkgmgr/package.go, pkgmgr/package_test.go
1. Exposes the OS and ARCH as template variables, making them available for package configurations.
2. Written an unit test function to validate proper injection of OS & ARCH into the template during installation.
Closes #343
=> feat(pkgmgr): expose os facts to packages

pkgmgr/state.go
Previously, we relied on the user's umask setting to ensure safety, but it's better to be explicit.
=> fix(pkgmgr): tighten up permissions on directories and files

README.md, cmd/cardano-up/list.go, cmd/cardano-up/list_test.go
1. Modified the default list-available to show only the latest version of each package.
2. Added a verbose (-v or --verbose) flag to show all the versions of each package.
Closes #352
=> feat(main): Filter list-available to latest

pkgmgr/package.go, pkgmgr/package_test.go
1. Added support for running a preStart script after install but before starting the service(s) for a package.
2. Added support running a preStop script before stopping the service(s) for a package.
3. Added a unit test function to validate both hook executions.
Closes #345 
Closes #250
=> feat(pkgmgr): Added support for preStart and preStop hook scripts

pkgmgr/package.go
Preallocating the strings will override the container's own built in configurations for these if they're not explicitly set in the package. This broke the `cardano-node` package's use of arguments to the entrypoint script.
=> fix: do not preallocate strings in package install
